import wx
from wx import *
app = App()
root = Frame(None,title="Stock",size=(1000,600))
panel = Panel(root)
panel.SetBackgroundColour("#C8E6C9")
mainbox = BoxSizer(VERTICAL)
def set_font(var):
    var.SetFont(Font(12,DECORATIVE,NORMAL,NORMAL))
def close_window(event):
    root.Close()
top = BoxSizer(HORIZONTAL)
logo = StaticBitmap(panel,1,Bitmap("F:\logo.png"))
top.Add(logo,5,EXPAND|ALL)
time = StaticText(panel,1,label="22:45:56")
time.SetFont(Font(22,DECORATIVE,NORMAL,BOLD))
close = Button(panel,label="X")
close.SetForegroundColour("white")
close.SetFont(Font(18,DECORATIVE,NORMAL,BOLD))
close.SetBackgroundColour("#F06292")
close.Bind(EVT_BUTTON,close_window,close)
top.Add(time,4,EXPAND|ALL,border=10)
top.Add(close,1,EXPAND|ALL,border=10)
mainbox.Add(top,1,EXPAND|ALL,border=10)

body = BoxSizer(HORIZONTAL)
bs1 = BoxSizer(VERTICAL)
form = GridSizer(2,3,20,20)
name = StaticText(panel,0,label="Name")
contact = StaticText(panel,0,label="Contact")
email = StaticText(panel,0,label="Email")
set_font(name)
set_font(contact)
set_font(email)
nametc = TextCtrl(panel)
contacttc = TextCtrl(panel)
emailtc = TextCtrl(panel)
set_font(nametc)
set_font(contacttc)
set_font(emailtc)
form.AddMany([
    (name),(contact),(email),
    (nametc,0,EXPAND|ALL),(contacttc,0,EXPAND|ALL),(emailtc,0,EXPAND|ALL)
])
bs1.Add(form,1,EXPAND|ALL,border=10)

entry = GridSizer(6,4,10,10)
product = StaticText(panel,0,label="Product",style=ALIGN_CENTER)
quantity = StaticText(panel,0,label="Quantity",style=ALIGN_CENTER)
amount = StaticText(panel,0,label="Amount",style=ALIGN_CENTER)
total = StaticText(panel,0,label="Total",style=ALIGN_CENTER)
set_font(product)
set_font(quantity)
set_font(amount)
set_font(total)
pro1 = TextCtrl(panel)
pro2 = TextCtrl(panel)
pro3 = TextCtrl(panel)
pro4 = TextCtrl(panel)
qty1 = TextCtrl(panel)
qty2 = TextCtrl(panel)
qty3 = TextCtrl(panel)
qty4 = TextCtrl(panel)
amount1 = TextCtrl(panel)
amount2 = TextCtrl(panel)
amount3 = TextCtrl(panel)
amount4 = TextCtrl(panel)
total1 = TextCtrl(panel)
total2 = TextCtrl(panel)
total3 = TextCtrl(panel)
total4 = TextCtrl(panel)

#default value
qty1.SetValue("0")
qty2.SetValue("0")
qty3.SetValue("0")
qty4.SetValue("0")
amount1.SetValue("0")
amount2.SetValue("0")
amount3.SetValue("0")
amount4.SetValue("0")
total1.SetValue("0")
total2.SetValue("0")
total3.SetValue("0")
total4.SetValue("0")

set_font(pro1)
set_font(pro2)
set_font(pro3)
set_font(pro4)
set_font(qty1)
set_font(qty2)
set_font(qty3)
set_font(qty4)
set_font(amount1)
set_font(amount2)
set_font(amount3)
set_font(amount4)
set_font(total1)
set_font(total2)
set_font(total3)
set_font(total4)
def total_amount(e):
    name_data = nametc.GetValue()
    contact_data = contacttc.GetValue()
    email_data = emailtc.GetValue()
    product1 = int(qty1.GetValue()) * int(amount1.GetValue())
    product2 = int(qty2.GetValue()) * int(amount2.GetValue())
    product3 = int(qty3.GetValue()) * int(amount3.GetValue())
    product4 = int(qty4.GetValue()) * int(amount4.GetValue())
    net_amount = product1 + product2 + product3 + product4
    gst = net_amount * 0.18
    total_amount = net_amount + gst
    total1.SetValue(str(product1))
    total2.SetValue(str(product2))
    total3.SetValue(str(product3))
    total4.SetValue(str(product4))
    text.SetValue("INVOICING SYSTEM\n\nName:\t"+name_data+"\nContact:\t"+contact_data+"\nEmail:\t"+email_data+
                  "\n\nSub Total:\t\t"+str(net_amount)+"\nGST(18%):\t"+str(gst)+"\nTotal:\t\t"+str(total_amount)+
                  "\n\n\nThank you for visiting us...:)")
totalbtn = Button(panel,label="Total")
orderbtn = Button(panel,label="Order")
managebtn = Button(panel,label="Manage")
settingbtn = Button(panel,label="Setting")
totalbtn.Bind(EVT_BUTTON,total_amount,totalbtn)
totalbtn.SetFont(Font(16,DECORATIVE,NORMAL,NORMAL))

managebtn.SetFont(Font(16,DECORATIVE,NORMAL,NORMAL))
orderbtn.SetFont(Font(16,DECORATIVE,NORMAL,NORMAL))
settingbtn.SetFont(Font(16,DECORATIVE,NORMAL,NORMAL))
totalbtn.SetBackgroundColour("#DCE775")
orderbtn.SetBackgroundColour("#4DB6AC")
settingbtn.SetBackgroundColour("#BA68C8")
managebtn.SetBackgroundColour("#FF8A65")
totalbtn.SetForegroundColour("white")
orderbtn.SetForegroundColour("white")
managebtn.SetForegroundColour("white")
settingbtn.SetForegroundColour("white")
entry.AddMany([
    (product),(quantity),(amount),(total),
    (pro1,1,EXPAND|ALL),(qty1,1,EXPAND|ALL),(amount1,1,EXPAND|ALL),(total1,1,EXPAND|ALL),
    (pro2,1,EXPAND|ALL),(qty2,1,EXPAND|ALL),(amount2,1,EXPAND|ALL),(total2,1,EXPAND|ALL),
    (pro3,1,EXPAND|ALL),(qty3,1,EXPAND|ALL),(amount3,1,EXPAND|ALL),(total3,1,EXPAND|ALL),
    (pro4,1,EXPAND|ALL),(qty4,1,EXPAND|ALL),(amount4,1,EXPAND|ALL),(total4,1,EXPAND|ALL),
    (totalbtn,1,EXPAND|ALL),(orderbtn,1,EXPAND|ALL),(managebtn,1,EXPAND|ALL),(settingbtn,1,EXPAND|ALL)
])
bs1.Add(entry,5,EXPAND|ALL,border=10)

body.Add(bs1,5,EXPAND|ALL)

text = TextCtrl(panel,style=TE_MULTILINE)
set_font(text)
body.Add(text,2,EXPAND|ALL)
mainbox.Add(body,5,EXPAND|ALL,border=10)
panel.SetSizer(mainbox)
root.Show()
app.MainLoop()